accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.contrib.auth.views import PasswordResetConfirmView
from .views import (
    favorite_add,
    delete_recipe,
    user_private_recipe_new,
    signup_view,
    login_view,
    logout_view,
    delete_account,
    profile_view,
)

app_name = "accounts"

class MyPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy('accounts:password_reset_complete')

urlpatterns = [
    path("fav/<int:id>/", favorite_add, name="favorite_add"),
    path("delete/<int:id>/", delete_recipe, name="delete_recipe"),
    path("recipe/new/", user_private_recipe_new, name="user_private_recipe_new"),
    path("signup/", signup_view, name="signup"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("delete_account/", delete_account, name="delete_account"),
    path("profile/", profile_view, name="profile"),

    path("password_reset/", 
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset_form.html', 
             email_template_name = 'registration/password_reset_email.html',
             success_url=reverse_lazy('accounts:password_reset_done')),
        name="password_reset"),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path("password_reset_complete/", auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name="password_reset_complete"),
]

recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    home,
    about,
    unsigned_user_redirect_recipes_list_page,
    signed_user_redirect_recipes_list_page,
    unsigned_user_redirect_recipes_detailed_page,
    signed_user_redirect_recipes_detailed_page,
    search_recipes_by_name,
    search_recipes_by_filters,
    search_recipes_by_ingredients,
    publish_comment,
    delete_comment,
    update_comment,
    user_submit_recipe,
)

app_name = "recipes"

urlpatterns = [
    path("", home),
    path("home/", 
         home, 
         name="home"
    ),
    path("about/", 
         about, 
         name="about"
    ),
    path(
        "recipes-list-unsigned-users/",
        unsigned_user_redirect_recipes_list_page,
        name="recipes_list_unsigned_users",
    ),
    path(
        "recipes-list-signed-users/",
        signed_user_redirect_recipes_list_page,
        name="recipes_list_signed_users",
    ),
    path(
        "recipes-submit/",
        user_submit_recipe,
        name="user_submit_recipe",
    ),
    path(
        "recipe_submitted_success.html",
        TemplateView.as_view(template_name="recipes/recipe_submitted_success.html"),
        name="user_submitted_recipe_success",
    ),
    path(
        "recipe_submitted_failed.html",
        TemplateView.as_view(template_name="recipes/recipe_submitted_failed.html"),
        name="user_submitted_recipe_failed",
    ),
    path("search-recipe-name/", 
         search_recipes_by_name, 
         name="search_recipes_name"
    ),
    path(
        "search-recipe-filters/",
        search_recipes_by_filters,
        name="search_recipes_filters",
    ),
    path(
        "search-recipe-ingredients/",
        search_recipes_by_ingredients,
        name="search_recipes_ingredients",
    ),
    path(
        "recipes-detail-unsigned-users/<pk>",
        unsigned_user_redirect_recipes_detailed_page,
        name="recipes_detail_unsigned_users",
    ),
    path(
        "recipes-detail-signed-users/<pk>",
        signed_user_redirect_recipes_detailed_page,
        name="recipes_detail_signed_users",
    ),
    path("publish-comment/<int:pk>/", 
         publish_comment, 
         name="publish_comment"
    ),
    path("delete-comment/<int:id>/", 
     delete_comment, 
         name="delete_comment"
    ),
    path("update-comment/<int:id>/", 
         update_comment, 
         name="update_comment"
    ),
]

recipes/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Recipe, RecipeComments, RecipeIngredients, RecipeAllergens, RecipeCookingInstructions, RecipeToolsNeeded, RecipeSimilarComplementary
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import UserSubmitRecipe, RecipeIngredientsForm, RecipeAllergensForm, RecipeCookingInstructionsForm, RecipeToolsForm, RecipeSimilarComplementaryForm
from django.forms import inlineformset_factory
import pandas as pd
from django.db.models import Q
from django.utils import timezone
from django.template.loader import render_to_string
from django.core.mail import EmailMessage



# Functions used to return appropriate views/html template for the recipes app depending on
# the URL
def home(request):
    return render(request, "recipes/home.html")

def about(request):
    return render(request, "recipes/about.html")

class RecipeListViewUnsignedUsers(ListView):
    model = Recipe
    template_name = "recipes/unsigned_users_recipes.html"

def unsigned_user_redirect_recipes_list_page(request):
    view = RecipeListViewUnsignedUsers.as_view()
    return view(request)

class RecipeListViewSignedUsers(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = "recipes/signed_users_recipes.html"

@login_required
def signed_user_redirect_recipes_list_page(request):
    view = RecipeListViewSignedUsers.as_view()
    return view(request)

class RecipeDetailViewUnsignedUsers(DetailView):
    model = Recipe
    template_name = "recipes/unsigned_users_recipes_details.html"

def unsigned_user_redirect_recipes_detailed_page(request, pk):
    view = RecipeDetailViewUnsignedUsers.as_view()
    return view(request, pk=pk)

class RecipeDetailViewSignedUsers(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = "recipes/signed_users_recipes_details.html"

@login_required
def signed_user_redirect_recipes_detailed_page(request, pk):
    view = RecipeDetailViewSignedUsers.as_view()
    return view(request, pk=pk)



# Takes the request coming from the web app on recipes that are searched by name \
# and returns the JSON response containing the recipes that match the search query.
def search_recipes_by_name(request):
    search_query = request.GET.get("query")
    matching_recipes = Recipe.objects.filter(recipe_name__icontains=search_query)

    recipes_json = [
        {
            "recipe_name": recipe.recipe_name,
            "recipe_origin_country": recipe.origin_country,
            "recipe_difficulty": recipe.difficulty,
            "recipe_category": recipe.recipe_category,
            "recipe_url": recipe.get_absolute_url(),
            "recipe_url_signed_users": recipe.get_absolute_url_signed_users(),
            "pic": recipe.pic.url,
        }
        for recipe in matching_recipes
    ]

    print(recipes_json)
    return JsonResponse({"recipes": recipes_json})


# Takes the request coming from the web app on recipes that are searched by filters \
# and returns the JSON response containing the recipes that match the search query.
def search_recipes_by_filters(request):
    search_query1 = request.GET.get("query1")
    search_query2 = request.GET.get("query2")
    search_query3 = request.GET.get("query3")
    search_query4 = request.GET.get("query4")

    # Initialize the queryset with all recipes
    matching_recipes = Recipe.objects.all()

    if search_query1:
        matching_recipes = matching_recipes.filter(
            origin_country__icontains=search_query1
        )

    if search_query2:
        matching_recipes = matching_recipes.filter(
            recipe_category__icontains=search_query2
        )

    if search_query3:
        if search_query3 == "1":
            matching_recipes = matching_recipes.filter(cooking_time__lte=15)
        elif search_query3 == "2":
            matching_recipes = matching_recipes.filter(cooking_time__lte=30)
        elif search_query3 == "3":
            matching_recipes = matching_recipes.filter(cooking_time__lte=45)
        elif search_query3 == "4":
            matching_recipes = matching_recipes.filter(cooking_time__lte=60)
        elif search_query3 == "5":
            matching_recipes = matching_recipes.filter(cooking_time__gt=60)

    if search_query4:
        if search_query4 == "1":
            matching_recipes = matching_recipes.filter(recipe_estimated_cost__lte=5)
        elif search_query4 == "2":
            matching_recipes = matching_recipes.filter(recipe_estimated_cost__lte=10)
        elif search_query4 == "3":
            matching_recipes = matching_recipes.filter(recipe_estimated_cost__lte=20)
        elif search_query4 == "4":
            matching_recipes = matching_recipes.filter(recipe_estimated_cost__lte=30)
        elif search_query4 == "5":
            matching_recipes = matching_recipes.filter(recipe_estimated_cost__gt=30)

    recipes_json = [
        {
            "recipe_name": recipe.recipe_name,
            "recipe_origin_country": recipe.origin_country,
            "recipe_difficulty": recipe.difficulty,
            "recipe_category": recipe.recipe_category,
            "recipe_url": recipe.get_absolute_url(),
            "recipe_url_signed_users": recipe.get_absolute_url_signed_users(),
            "pic": recipe.pic.url,
        }
        for recipe in matching_recipes
    ]

    return JsonResponse({"recipes": recipes_json})


# Takes the request coming from the web app on recipes that are searched by ingredients
# and returns the JSON response containing the recipes that match the search query.
def search_recipes_by_ingredients(request):
    # Retrieves the 'query' parameter from the GET request
    search_query = request.GET.get("query")
    # Splits the search query (a comma-separated list of ingredients) into individual ingredients \
    # and stores them in a list called 'ingredients'. The strip() is used to remove \
    # any leading or trailing whitespaces from each ingredient.
    ingredients = [ingredient.strip() for ingredient in search_query.split(",")]

    # Retrieves all recipes that contain the first ingredient in the ingredients list.
    matching_recipes = Recipe.objects.filter(
        recipe_ingredients__ingredient_name__icontains=ingredients[0]
    )

    # Code iterates over the remaining ingredients of the list (if any) using a for loop.
    # 'for ingredient in ingredients[1:]:' iterates over each ingredient in the list, skipping the \
    # first one.
    for ingredient in ingredients[1:]:
        # For each ingredient in the loop, it further filters the recipes to find those containing \
        # the current ingredient.
        matching_recipes = matching_recipes.filter(
            recipe_ingredients__ingredient_name__icontains=ingredient
        )

    # distinct() method is used to remove duplicates recipes if one recipe contains more than one \
    # of the same ingredient in his list (e.g.: a recipe contains both 'granulated sugar' and \
    # 'powdered sugar' in its ingredients list, and the user searches for 'sugar'). With dinstinct() \
    # the recipe will only appear once in the search results instead of twice.
    matching_recipes = matching_recipes.distinct()

    recipes_json = [
        {
            "recipe_name": recipe.recipe_name,
            "recipe_origin_country": recipe.origin_country,
            "recipe_difficulty": recipe.difficulty,
            "recipe_category": recipe.recipe_category,
            "recipe_url": recipe.get_absolute_url(),
            "recipe_url_signed_users": recipe.get_absolute_url_signed_users(),
            "pic": recipe.pic.url,
        }
        for recipe in matching_recipes
    ]

    return JsonResponse({"recipes": recipes_json})

# Logic to allow users to add comments to recipes
def publish_comment(request, pk):
    if request.method == 'POST':
        comment_text = request.POST.get('comment') 
        recipe = Recipe.objects.get(pk=pk)
        recipe.comments.create(text=comment_text, user=request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def delete_comment(request, id):
    comment = get_object_or_404(RecipeComments, id=id)
    comment.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def update_comment(request, id):
    comment = get_object_or_404(RecipeComments, id=id)
    comment.text = request.POST.get('comment')
    comment.updated_at = timezone.now() 
    comment.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

# Logic allowing users to submit a recipe by email via the web app (submit recipe page)
def user_submit_recipe(request):
    RecipeIngredientsFormSet = inlineformset_factory(Recipe, RecipeIngredients, form=RecipeIngredientsForm, extra=1, can_delete=True)
    RecipeAllergensFormSet = inlineformset_factory(Recipe, RecipeAllergens, form=RecipeAllergensForm, extra=1, can_delete=True)
    RecipeCookingInstructionsFormSet = inlineformset_factory(Recipe, RecipeCookingInstructions, form=RecipeCookingInstructionsForm, extra=1, can_delete=True)
    RecipeToolsFormSet = inlineformset_factory(Recipe, RecipeToolsNeeded, form=RecipeToolsForm, extra=1, can_delete=True)
    RecipeSimilarComplementaryFormSet = inlineformset_factory(Recipe, RecipeSimilarComplementary, form=RecipeSimilarComplementaryForm, extra=1, can_delete=True)

    if request.method == 'POST':
        form = UserSubmitRecipe(request.POST, request.FILES)
        formset = RecipeIngredientsFormSet(request.POST, request.FILES, prefix='ingredients')
        allergens_formset = RecipeAllergensFormSet(request.POST, request.FILES, prefix='allergens')
        cooking_instructions_formset = RecipeCookingInstructionsFormSet(request.POST, request.FILES, prefix='cooking_instructions')

recipes/templates/recipes/about.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="{% static 'recipes/js/javascript.js' %}" defer></script>
    <title>Cuisine atlas</title>
    <link rel="shortcut icon" href="{% static 'recipes/img/website-logo.png' %}" type="image/x-icon">
    <link rel="manifest" href="{% static 'recipes/manifest.json' %}">
</head>

<main>
    <header>
        <div class="header-display">
            <nav class="navbar navbar-expand-md navbar-light justify-content-end">
                <div class="logo-container">
                    <img src="{% static 'recipes/img/website-logo.png' %}" alt="website-logo" class="logo-image">
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            {% if user.is_authenticated %}
                            <!-- Show nothing when user is logged in -->
                            {% else %}
                            <a class="nav-link" href="{% url 'recipes:home' %}">Home</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'recipes:recipes_list_signed_users' %}">
                                Recipes
                            </a>
                            {% else %}
                            <a class="nav-link" href="{% url 'recipes:recipes_list_unsigned_users' %}">
                                Recipes
                            </a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'accounts:logout' %}">
                                Logout
                            </a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <body>
        <div class="image-background-about-page">
            <div class="row welcome-boxes">
                <div class="col-xl-8 col-lg-8 col-md-8 col-sm-10 col-10">
                    <div class="welcome-box-1">
                        <h1 class="website-title">A tablespoon of discovery</h1>
                        <br>
                        <h2 class="website-subtitle">Our mission</h2>
                        <p>To take people on a traveling journey one meal at a time, by offering a variety of accessible
                            traditional recipes from all around the world.</p>
                        <br>
                        <h2 class="website-subtitle">Our goal</h2>
                        <p>We've designed our website specifically to open the world's gastronomic doors to food lovers.
                            Our aim is to display as many recipes as possible from all corners of
                            the globe, so that you can discover new flavors, new cuisines and simply immerse yourself in
                            new cultures! Whether you're looking for an original quick meal for an evening with
                            friends, a top-of-the-range meal for a romantic dinner or a simple family meal on a
                            weekday, our cuisine atlas have the right recipes for you.</p>
                        <br>
                        <h2 class="website-subtitle">What sets us apart</h2>
                        <p>We know that cooking international dishes can sometimes be a challenge. That's why we offer
                            clear and simple cooking instructions for each recipe, as well as several substitutes for
                            the
                            original ingredients that may not be available in your area. With our Cuisine Atlas, cooking
                            a
                            delicious Indian, Brazilian or Greek recipe from home, with or without all the original
                            ingredients, is
                            possible. Our website also offer advanced search options, so you can find the type of
                            cuisine you want very
                            quickly.</p>
                        <br>
                        <h2 class="website-subtitle">Contribute!</h2>
                        <p>Want to contribute? If you'd like to share one of your great recipes with the world, <a
                                href="{% url 'recipes:user_submit_recipe' %}" target="_blank">share it with us here</a>.
                            We'll receive your recipe, and if it seems complete after review, we'll gladly publish it.
                        </p>
                        <br>
                        <h2 class="website-subtitle">Contact</h2>
                        <p>If you have any questions or suggestions, you can contact us at the following adress: <br>
                            <a href="mailto:atablespoonofdiscovery@gmail.com" class="email-line-wrap">atablespoonofdiscovery@gmail.com
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <footer>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <script src="{% static 'recipes/js/javascript.js' %}"></script>
</main>

</html>

recipes/templates/recipes/recipe_submitted_failed.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="{% static 'recipes/js/javascript.js' %}" defer></script>
    <title>Cuisine atlas</title>
    <link rel="shortcut icon" href="{% static 'recipes/img/website-logo.png' %}" type="image/x-icon">
    <link rel="manifest" href="{% static 'recipes/manifest.json' %}">
</head>

<main>
    <header>
        <div class="header-display">
            <nav class="navbar navbar-expand-md navbar-light nav justify-content-end">
                <div class="logo-container">
                    <img src="{% static 'recipes/img/website-logo.png' %}" alt="ac-logo" class="logo-image">
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse nav justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            {% if user.is_authenticated %}
                            <!-- Show nothing when user is logged in -->
                            {% else %}
                            <a class="nav-link" href="{% url 'recipes:home' %}">Home</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'recipes:recipes_list_signed_users' %}">
                                Recipes
                            </a>
                            {% else %}
                            <a class="nav-link" href="{% url 'recipes:recipes_list_unsigned_users' %}">
                                Recipes
                            </a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'recipes:about' %}">About</a>
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'accounts:logout' %}">
                                Logout
                            </a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <body>
        <div class="image-background-recipe-submit-failed-page">
            <div class="row welcome-boxes">
                <div class="col-xl-6 col-lg-6 col-md-8 col-sm-10 col-10">
                    <div class="welcome-box-1">
                        <h1 class="website-title">A tablespoon of discovery</h1>
                        <br>
                        <h2 class="website-subtitle">An error has occurred. The recipe was not sent.</h2>
                        <br>
                        <div class="container">
                            <div class="row">
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12 buttons-bottom-padding">
                                    {% if user.is_authenticated %}
                                    <a href="{% url 'accounts:logout' %}" class="btn btn-dark btn-sm w-100">
                                        Logout
                                    </a>
                                    {% else %}
                                    <a href="{% url 'recipes:home' %}" class="btn btn-dark btn-sm w-100">Home</a>
                                    {% endif %}
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12 buttons-bottom-padding">
                                    <a href="{% url 'recipes:user_submit_recipe' %}" class="btn btn-dark btn-sm w-100">
                                        Try again
                                    </a>
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12 buttons-bottom-padding">
                                    {% if user.is_authenticated %}
                                    <a class="btn btn-dark btn-sm w-100" href="{% url 'recipes:recipes_list_signed_users' %}">
                                        See recipes
                                    </a>
                                    {% else %}
                                    <a class="btn btn-dark btn-sm w-100"
                                        href="{% url 'recipes:recipes_list_unsigned_users' %}">
                                        See recipes
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <footer>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <script src="{% static 'recipes/js/javascript.js' %}"></script>
</main>

</html>

recipes/templates/recipes/user_submit_recipe_email.html
<!-- Used to format the information sent by email when a user submits a recipe. -->

<h1>Recipe submission</h1>
<h2>Basic information</h2>
<p><b>Recipe name:</b> {{ recipe_name }}</p>
<p><b>Description:</b> {{ description }}</p>
<p><b>Special note:</b> {{ special_note }}</p>
<p><b>Cooking time:</b> {{ cooking_time }}</p>
<p><b>Number of portions:</b> {{ number_of_portions }}</p>
<p><b>Recipe estimated cost:</b> {{ recipe_estimated_cost }}</p>
<p><b>Recipe origin country:</b> {{ origin_country }}</p>
<p><b>Recipe category:</b> {{ recipe_category }}</p>
<p><b>Recipe picture:</b> {{ pic }}</p>
<h2>Ingredients</h2>
<p><b>Ingredient:</b> {{ ingredients }}</p>
<h2>Allergens</h2>
<p><b>Allergens:</b> {{ allergens }}</p>
<h2>Cooking instructions</h2>
<p><b>Cooking instructions:</b> {{ cooking_instructions }}</p>
<h2>Recipe tools</h2>
<p><b>Recipe tools:</b> {{ recipe_tools }}</p>
<h2>Similar / complementary recipes</h2>
<p><b>Similar / complementary recipes:</b> {{ recipe_similar_complementary }}</p>