accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.contrib.auth.views import PasswordResetConfirmView
from .views import (
    favorite_add,
    delete_recipe,
    user_private_recipe_new,
    signup_view,
    login_view,
    logout_view,
    delete_account,
    profile_view,
)

app_name = "accounts"

class MyPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy('accounts:password_reset_complete')

urlpatterns = [
    path("fav/<int:id>/", favorite_add, name="favorite_add"),
    path("delete/<int:id>/", delete_recipe, name="delete_recipe"),
    path("recipe/new/", user_private_recipe_new, name="user_private_recipe_new"),
    path("signup/", signup_view, name="signup"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("delete_account/", delete_account, name="delete_account"),
    path("profile/", profile_view, name="profile"),

    path("password_reset/", 
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset_form.html', 
             email_template_name = 'registration/password_reset_email.html',
             success_url=reverse_lazy('accounts:password_reset_done')),
        name="password_reset"),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path("password_reset_complete/", auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name="password_reset_complete"),
]

recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    home,
    about,
    unsigned_user_redirect_recipes_list_page,
    signed_user_redirect_recipes_list_page,
    unsigned_user_redirect_recipes_detailed_page,
    signed_user_redirect_recipes_detailed_page,
    search_recipes_by_name,
    search_recipes_by_filters,
    search_recipes_by_ingredients,
    publish_comment,
    delete_comment,
    update_comment,
    user_submit_recipe,
)

app_name = "recipes"

urlpatterns = [
    path("", home),
    path("home/", 
         home, 
         name="home"
    ),
    path("about/", 
         about, 
         name="about"
    ),
    path(
        "recipes-list-unsigned-users/",
        unsigned_user_redirect_recipes_list_page,
        name="recipes_list_unsigned_users",
    ),
    path(
        "recipes-list-signed-users/",
        signed_user_redirect_recipes_list_page,
        name="recipes_list_signed_users",
    ),
    path(
        "recipes-submit/",
        user_submit_recipe,
        name="user_submit_recipe",
    ),
    path(
        "recipe_submitted_success.html",
        TemplateView.as_view(template_name="recipes/recipe_submitted_success.html"),
        name="user_submitted_recipe_success",
    ),
    path(
        "recipe_submitted_failed.html",
        TemplateView.as_view(template_name="recipes/recipe_submitted_failed.html"),
        name="user_submitted_recipe_failed",
    ),
    path("search-recipe-name/", 
         search_recipes_by_name, 
         name="search_recipes_name"
    ),
    path(
        "search-recipe-filters/",
        search_recipes_by_filters,
        name="search_recipes_filters",
    ),
    path(
        "search-recipe-ingredients/",
        search_recipes_by_ingredients,
        name="search_recipes_ingredients",
    ),
    path(
        "recipes-detail-unsigned-users/<pk>",
        unsigned_user_redirect_recipes_detailed_page,
        name="recipes_detail_unsigned_users",
    ),
    path(
        "recipes-detail-signed-users/<pk>",
        signed_user_redirect_recipes_detailed_page,
        name="recipes_detail_signed_users",
    ),
    path("publish-comment/<int:pk>/", 
         publish_comment, 
         name="publish_comment"
    ),
    path("delete-comment/<int:id>/", 
     delete_comment, 
         name="delete_comment"
    ),
    path("update-comment/<int:id>/", 
         update_comment, 
         name="update_comment"
    ),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager)
from recipes.models import Recipe

class UserManager(BaseUserManager):
    # Creates and saves a user with the given email and password.
    def create_user(self, email, full_name, password=None, is_active=True, is_staff=False, is_admin=False):
        if not email:
            raise ValueError('Users must have an email address')
        if not password:
            raise ValueError('Users must have a password')
        if not full_name:
            raise ValueError('Users must have a full name')
        
        user_obj = self.model(
            email=self.normalize_email(email),
            full_name=full_name
        )

        user_obj.set_password(password)
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.active = is_active
        user_obj.save(using=self._db)
        return user_obj

    # Creates and saves a staff user with the given email and password.
    def create_staffuser(self, email, full_name, password=None):
        user = self.create_user(
            email,
            full_name,
            password=password,
            is_staff=True
        )
        return user
    
    # Creates and saves a staff user with the given email and password.
    def create_superuser(self, email, full_name, password=None):
        user = self.create_user(
            email,
            full_name,
            password=password,
            is_staff=True,
            is_admin=True
        )
        return user

class User(AbstractBaseUser):
        email = models.EmailField(max_length=255, unique=True)
        full_name = models.CharField(max_length=255)
        is_active = models.BooleanField(default=True)
        staff = models.BooleanField(default=False) 
        admin = models.BooleanField(default=False)
        timestamp = models.DateTimeField(auto_now_add=True)
        favorite_recipes = models.ManyToManyField(Recipe, related_name='user_favorite_recipes',  default=[], blank=True)
        user_created_recipes = models.ManyToManyField(Recipe, related_name='created_by',  default=[], blank=True)

        # USERNAME_FIELD and password are required by default
        USERNAME_FIELD = 'email'
        REQUIRED_FIELDS = ['full_name']

        objects = UserManager()

        def __str__(self):
            if self.full_name:
                return self.full_name
            return self.email

        def get_full_name(self):
            return self.email

        def get_short_name(self):
            return self.email
        
        def has_perm(self, perm, obj=None):
            "Does the user have a specific permission?"
            # Simplest possible answer: Yes, always
            return True

        def has_module_perms(self, app_label):
            "Does the user have permissions to view the app `app_label`?"
            # Simplest possible answer: Yes, always
            return True

        @property
        def is_staff(self):
            "Is the user a member of staff?"
            return self.staff

        @property
        def is_admin(self):
            "Is the user a admin member?"
            return self.admin

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserAdminCreationForm, UserCreatePrivateRecipe, RecipeIngredientsFormSet, RecipeAllergensFormSet, RecipeCookingInstructionsFormSet
from recipes.models import Recipe, RecipeIngredients

def signup_view(request):
    if request.method == 'POST':
        # Form taken from forms.py
        form = UserAdminCreationForm(request.POST) 

        if form.is_valid():
            form.save()
            return redirect('accounts:login')
        
        else:
            print("User creation failed")
            print(form.errors)
            
    else:
        # Form taken from forms.py
        form = UserAdminCreationForm()  

    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    error_message = None
    # Default Django form for handling user authentication
    form = AuthenticationForm()

    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("recipes:recipes_list_signed_users")
            
        else:
            error_message = "ooops.. something went wrong"

    # Prepare data to send from view.py to template.html
    context = {"form": form, "error_message": error_message}
    return render(request, "accounts/login.html", context)


def logout_view(request):
    logout(request)
    return render(request, 'accounts/logout.html')


def delete_account(request):
    if not request.user.is_authenticated:
    # Redirect to the home page if user try to go back on the delete account page after moving from it
        return redirect('recipes:home')

    user = request.user
    logout(request)
    user.delete()
    return render(request, 'accounts/account-deleted.html')


# Function to display the user's profile page information
@login_required
def profile_view(request):
    favorite_recipes = favorite_list(request)
    created_recipes = created_recipe(request)
    form = UserCreatePrivateRecipe()
    formset = RecipeIngredientsFormSet(prefix='formset')
    allergens_formset = RecipeAllergensFormSet(prefix='allergens')
    cooking_instructions_formset = RecipeCookingInstructionsFormSet(prefix='cooking_instructions')

    return render(
        request,
        'accounts/profile.html',
        {
            'favorite_recipes': favorite_recipes,
            'created_recipes': created_recipes,
            'form': form,
            'formset': formset,
            'allergens_formset': allergens_formset,
            'cooking_instructions_formset': cooking_instructions_formset,
        }
    )


# Used to add or remove recipes from the user's favorites.
def favorite_add(request, id):
    recipe = get_object_or_404(Recipe, id=id)

    if recipe.favorites.filter(id=request.user.id).exists():
        recipe.favorites.remove(request.user)
    else:
        recipe.favorites.add(request.user)

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


# Used to display recipes that are favorited by user.
def favorite_list(request):
    favorites = request.user.favorites.all()
    favorite_recipes = Recipe.objects.filter(favorites=request.user)
    return favorite_recipes


# Used to display recipes that are created by user.
def created_recipe(request):
    created_recipes = request.user.created_recipes.all()
    return created_recipes


def delete_recipe(request, id):
    recipe = get_object_or_404(Recipe, id=id)
    recipe.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def user_private_recipe_new(request):
    if request.method == "POST":
        form = UserCreatePrivateRecipe(request.POST, request.FILES)
        formset = RecipeIngredientsFormSet(request.POST, prefix='formset')
        allergens_formset = RecipeAllergensFormSet(request.POST, prefix='allergens')
        cooking_instructions_formset = RecipeCookingInstructionsFormSet(request.POST, prefix='cooking_instructions')

        if form.is_valid() and formset.is_valid() and allergens_formset.is_valid() and cooking_instructions_formset.is_valid():
            recipe = form.save(commit=False)
            recipe.user = request.user
            recipe.save()

            formset.instance = recipe
            formset.save()

            allergens_formset.instance = recipe
            allergens_formset.save()

            cooking_instructions_formset.instance = recipe
            cooking_instructions_formset.save()

            return HttpResponseRedirect(request.META['HTTP_REFERER'])
        
        else:
            print(form.errors)
            print(formset.errors)
            print(allergens_formset.errors)
            print(cooking_instructions_formset.errors)

    else:
        form = UserCreatePrivateRecipe()
        formset = RecipeIngredientsFormSet(prefix='formset')
        allergens_formset = RecipeAllergensFormSet(prefix='allergens')
        cooking_instructions_formset = RecipeCookingInstructionsFormSet(prefix='cooking_instructions')

    return render(request, 'accounts/profile.html', {'form': form, 'formset': formset, 'allergens_formset': allergens_formset, 'cooking_instructions_formset': cooking_instructions_formset})

accounts/templates/accounts/account-deleted.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Cuisine atlas</title>
    <link rel="shortcut icon" href="{% static 'accounts/img/website-logo.png' %}" type="image/x-icon">
    <link rel="manifest" href="{% static 'recipes/manifest.json' %}">
</head>

<main>
    <header>
        <div class="header-display">
            <nav class="navbar navbar-expand-md navbar-light nav justify-content-end">
                <div class="logo-container">
                    <img src="{% static 'accounts/img/website-logo.png' %}" alt="ac-logo" class="logo-image">
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse nav justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'recipes:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'recipes:recipes_list_unsigned_users' %}">Recipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'recipes:about' %}">About</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <body>
        <div class="image-background">
            <div class="row delete-account-page-action-boxes">
                <div class="col-xl-6 col-lg-6 col-md-8 col-sm-10 col-10">
                    <div class="delete-account-page-action-box-1">
                        <h1 class="website-title">A tablespoon of discovery</h1>
                        <br>
                        <h2 class="page-main-message">Account deleted</h2>
                        <br>
                        <p>You’ve successfully deleted your account.</p>
                        <p>Come back whenever in need of more <b>amazing recipes!</b></p> 
                        <br>
                        <div class="container">
                            <div class="row">
                                <div class="col-xl-2 col-lg-2 col-md-2 col-sm-1">                                    
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-12 delete-page-buttons-bottom-margin">
                                    <a class="btn btn-dark btn-sm w-100" href="{% url 'recipes:home' %}">
                                        Home
                                    </a>
                                </div>
                                <br>
                                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-12">
                                    <a class="btn btn-dark btn-sm w-100" href="{% url 'accounts:signup' %}">
                                        Sign up
                                    </a>
                                </div>     
                                <div class="col-xl-2 col-lg-2 col-md-2 col-sm-1">                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <footer>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <script src="{% static 'recipes/js/javascript.js' %}"></script>
</main>

</html>

accounts/templates/accounts/login.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Cuisine atlas</title>
    <link rel="shortcut icon" href="{% static 'accounts/img/website-logo.png' %}" type="image/x-icon">
    <link rel="manifest" href="{% static 'recipes/manifest.json' %}">
</head>

<main>
    <header>
        <div class="header-display">
            <nav class="navbar navbar-expand-md navbar-light justify-content-end">
                <div class="logo-container">
                    <img src="{% static 'accounts/img/website-logo.png' %}" alt="ac-logo" class="logo-image">
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse nav justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'recipes:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'recipes:recipes_list_unsigned_users' %}">Recipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'recipes:about' %}">About</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <body>
        <div class="image-background">
            <div class="row action-boxes">
                <div class="col-xl-6 col-lg-6 col-md-8 col-sm-10 col-10">
                    <div class="action-box-1 login-page-white-background-bottom-padding">
                        <h1 class="website-title">A tablespoon of discovery</h1>
                        <br>
                        <h2 class="page-main-message">Log in</h2>
                        <br>
                        <div class="container">
                            <div class="row">
                                {% if form.non_field_errors %}
                                <div class="custom-alert-top-one alert-danger">
                                    <strong>Error(s):</strong>
                                    <ul class="error-message">
                                        {% for error in form.non_field_errors %}
                                        <span class="error-text">{{ error }}</span>
                                        {% endfor %}
                                    </ul>
                                </div>
                                {% endif %}
                            </div>
                            <div class="row">
                                <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-2">
                                </div>
                                <div class="col-xl-10 col-lg-10 col-md-10 col-sm-10 col-8">
                                    <form action="{% url 'accounts:login' %}" method="POST"
                                        class="row justify-content-center">
                                        {% csrf_token %}
                                        <h6>Email</h6>
                                        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-10 col-12 login-form">
                                            <div class="input-group">
                                                <input id="username-field" name="{{ form.username.name }}" type="text"
                                                    class="form-control" aria-label="username-login"
                                                    aria-describedby="email-field">
                                            </div>
                                            {% if form.username.errors %}
                                            <div class="custom-alert alert-danger">
                                                {% for error in form.username.errors %}
                                                <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                            {% endif %}
                                        </div>
                                        <h6>Password</h6>
                                        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-10 col-12 login-form">
                                            <div class="input-group">
                                                <input id="password-field" name="{{ form.password.name }}"
                                                    type="password" class="form-control" aria-label="password-login"
                                                    aria-describedby="password-field">
                                            </div>
                                            {% if form.password.errors %}
                                            <div class="custom-alert alert-danger">
                                                {% for error in form.password.errors %}
                                                <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                            {% endif %}
                                        </div>
                                        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-10 col-10 login-button">
                                            <button type="submit" class="btn btn-dark btn-sm" id="login-button"
                                                data-bs-dismiss="modal">Login</button>
                                        </div>
                                    </form>
                                    <a href="{% url 'accounts:signup' %}" class="signup-link">Sign up</a>
                                    <br>
                                    <a href="{% url 'accounts:password_reset' %}" class="forgot-password-link">Forgot password?</a>
                                </div>
                                <div class="col-xl-1 col-lg-1 col-md-1 col-sm-1 col-2">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <footer>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <script src="{% static 'recipes/js/javascript.js' %}"></script>
</main>

</html>

accounts/templates/accounts/password_reset_complete.html
{% load static %}
{% block content %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Cuisine atlas</title>
    <link rel="shortcut icon" href="{% static 'accounts/img/website-logo.png' %}" type="image/x-icon">
    <link rel="manifest" href="{% static 'recipes/manifest.json' %}">
</head>

<main>
    <header>
        <div class="header-display">
            <nav class="navbar navbar-expand-md navbar-light justify-content-end">
                <div class="logo-container">
                    <img src="{% static 'accounts/img/website-logo.png' %}" alt="ac-logo" class="logo-image">
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse nav justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'recipes:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'recipes:recipes_list_unsigned_users' %}">Recipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'recipes:about' %}">About</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <body>
        <div class="image-background">
            <div class="row action-boxes">
                <div class="col-xl-6 col-lg-6 col-md-8 col-sm-10 col-10">
                    <div class="action-box-1 reset-password-page4-white-background-bottom-padding">
                        <h1 class="website-title">A tablespoon of discovery</h1>
                        <br>
                        <h2 class="page-main-message">Password changed!</h2>
                        <br>
                        <div class="row">
                            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-2">
                            </div>
                            <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-12">
                                <div class="row justify-content-center">
                                    <p>Password reset complete.
                                        <br>
                                        You can now login with your new password.
                                        <br>
                                        <br>
                                    </p>
                                    <a class="btn btn-dark btn-sm w-50" href="{% url 'accounts:login' %}">
                                        Log in
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-2">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>

    <footer>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <script src="{% static 'recipes/js/javascript.js' %}"></script>
</main>

</html>
{% endblock %}